services:
  web:
    build: .
    env_file: .env
    expose:
      - "8000"
    networks:
      - appnet

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
    networks:
      - appnet

networks:
  appnet:
    driver: bridge