networks:
  mynetwork:
    driver: bridge

services:
  web:
    build: .
    env_file: .env
    expose:
      - "8000"
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
    networks:
      - mynetwork
