version: '3.8'

services:
  web:
    build: .
    restart: always
    env_file: .env
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    depends_on:
      - nginx
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
      - certbot_data:/etc/letsencrypt
      - certbot_logs:/var/log/letsencrypt

volumes:
  static_volume:
  media_volume:
  certbot_data:
  certbot_logs: