---
- hosts: django_server
  become: yes
  tasks:
    - name: Update APT cache and install prerequisites
      apt:
        update_cache: yes
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present

    - name: Install Docker and related packages
      apt:
        update_cache: yes
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Clone project from GitHub
      git:
        repo: "git@github.com:Friedox/test-task-django-stripe.git"
        dest: /home/ubuntu/test-task-django-stripe
        version: "main"
        force: yes
        accept_hostkey: yes
        key_file: "/root/.ssh/id_ed25519"

    - name: Copy local .env file to server
      copy:
        src: ../.env
        dest: /home/ubuntu/test-task-django-stripe/.env
        mode: '0600'

    - name: Bring up the application with Docker Compose
      command: docker-compose up -d --build
      args:
        chdir: /home/ubuntu/test-task-django-stripe